ktor:
  application:
    modules:
      - dev.hijikatanasu.ApplicationKt.module
  deployment:
    port: 8080

database:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/figure_manager_db"
  user: "postgres"
  password: "password"